export const symbols = {
    "BTCUSDT": {description: "Bitcoin", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    "ETHUSDT": {description: "Ethereum", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png"},
    "DOGEUSDT": {description: "Dogecoin", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png"},
    "SHIBUSDT": {description: "Shiba Inu", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png"},
    "SOLUSDT": {description: "Solana", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png"},
    "AVAXUSDT": {description: "Avalanche", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png"},
    "LUNAUSDT": {description: "Terra", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png"},
    "DOTUSDT": {description: "Polkadot", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png"},
    "LINKUSDT": {description: "Chainlink", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png"},
    "UNIUSDT": {description: "Uniswap", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png"},
    "MATICUSDT": {description: "Polygon", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png"},
    "ALGOUSDT": {description: "Algorand", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png"},
    "MANAUSDT": {description: "Decentraland", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/5719.png"},
    "LTCUSDT": {description: "Litecoin", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png"},
    "XLMUSDT": {description: "Stellar", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/512.png"},
    "XRPUSDT": {description: "XRP", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png"},
    "BCHUSDT": {description: "Bitcoin Cash", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png"},
    "FILUSDT": {description: "Filecoin", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/7388.png"},
    "XMRUSDT": {description: "Monero", image: "https://s2.coinmarketcap.com/static/img/coins/64x64/328.png"},
}